### ISSUE TITLE
Light version with bigger contrast

### ISSUE THREAD

**Issue by kristijanhusak** [sainnhe/edge#18]
Hi,

would you consider adding a light version that has more contrast?
Current light version foreground is a bit too bright, I would like to have more contrast between foreground and background.
Ideally, background would be completely white, and "Normal" foreground would be completely black. This doesn't look good when I change only those 2 values because normal contrast is too big in compare to other colors (Red, blue, etc.).
I've used this colorscheme before https://github.com/habamax/vim-polar which does this nicely, but I want to switch to yours because of the dark version and treesitter support.

If you would consider this, I could make a PR with a light version that has a stronger contrast and we can discuss it.

**Comment by sainnhe** [comment]
It's intentional. To get a higher contrast, all you need to do is:

- Increasing the contrast of Red.
- Using a more vibrant color of Blue, just like what it is in atom one.

Then increase the contrast of the Black color, you should get a satisfactory result.

But as I said in readme, this color scheme is basically a mixture of atom one and material, and I personally prefer the blue color in material light, and the current blue color is based on material light.

So I'm not going to change it. If you want to increase the contrast, fork this repo and try the steps I said above, maybe then maintain your own branch. This is an open source project, feel free to modify the color code ;)

**Comment by kristijanhusak** [comment]
Ok, thanks :-)

**Comment by kristijanhusak** [comment]
@sainnhe would you consider adding it as an additional style? I didn't mean to change the original colors, I just wanted to introduce additional light palette.
I know I can fork it and adapt it, but I like to keep originals in order to keep everything up to date :)

**Comment by sainnhe** [comment]
Sorry but I'm not interested in this, if I want to use a higher contrast variant, then I'm going to use atom one light instead.

**Comment by kristijanhusak** [comment]
Ok, thanks. Sorry for being pushy :)
