### ISSUE TITLE
Add theme for exa

### ISSUE THREAD

**Issue by winston0410** [sainnhe/edge#30]
It will be awsome if edge can be extended to [exa](https://the.exa.website/docs/colour-themes), but I found it difficult to contribute, as exa accepts ANSI escape code instead of HEX. Is it possible to convert HEX to ANSI escape code and keep the color as similar as possible? I would love to learn from the experienced who have contributed to this repo.

**Comment by sainnhe** [comment]
I have no idea how to convert HEX color code to ANSI escape code because this theme is mainly designed for true colors.

But there is a possible solution to use the exact colors of this theme in exa:

The range of ANSI escape code is 1~256, but the first 16 numbers are very special, they are controlled by the theme of your terminal emulator.

So you can simply use 1~16 to set $LS_COLORS, and then use this color scheme in your terminal emulator.

**Comment by winston0410** [comment]
Right i was going to ask for `LS_COLORS` as well. I guess I could make a mapping for those 16 colors and contribute them?

I am using alacritty right now, i will try to map those colors to it i guess
