### ISSUE TITLE
Some suggestions for the choice of colours when using LaTeX

### ISSUE THREAD

**Issue by dlejay** [sainnhe/edge#32]
I am a daily user of LaTeX + ``edge``.

As a LaTeX user, I am super grateful that ``edge`` has dedicated LaTeX colouring.

There is one case where the choice of colours is not optimal in my opinion:
when drawing a diagram with ``tikzcd``, the block of code is usually a mix of red
and orange.
Red because all ``texMathCmd`` are ``RedItalic``.
Orange because ``texMathZone`` is ``Special`` and ``texTabularChar`` is ``SpecialChar``.

I have a couple suggestions to make this easier to read:
1. (big change) I believe the colour Red is the most visible colour to the human eye and it should be used sparingly. Perhaps, one could assign a different colour to ``texMathCmd``
2. (small change) The colour assigned to ``texTabularChar`` should not be too close to the one of ``texMathCmd`` and ``texMathZone`` so that the eye can navigate easily in of tabular environments.

**Comment by sainnhe** [comment]
I'd suggest you to open a PR though, because I don't use latex, so this file type is only basically optimized, there might be some flaws. If you often use latex, I think you can make better decisions on colors than me.

But of course if you are somewhat busy recently, I'm going to optimize latex based on your suggestions when I have time.
