### ISSUE TITLE
Curly brace not colored in Template literal

### ISSUE THREAD

**Issue by leiswatch** [sainnhe/edge#34]
Hey! I wanted to thank you for this amazing colorscheme, I love it. There is just one small issue that is a little bit annoying - in Javascript/Typescript files, the closing curly brace of a placeholder in template literal is not colored. Is there a way to fix this? Thanks!

![image](https://user-images.githubusercontent.com/17877481/121256961-6ab3d580-c8ad-11eb-93c3-b0422c68d604.png)

**Comment by leiswatch** [comment]
---
name: Curly brace not colored in Template literal
about: Closing curly brace in Template literal is not colored when used with treesitter
title: ''
labels: bug
assignees: ''

---



- `Operating system/version`: Linux archlinux 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux
- `Terminal emulator/version`: Gnome Terminal 3.40.2
- `echo $TERM`: xterm-256color
- `vim --version` or `nvim --version`: NVIM v0.5.0-dev+1384-gf2906a466


```
Linux archlinux 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux

Gnome Terminal 3.40.2
```

### Minimal vimrc that can reproduce this bug

```vim

```

### Steps to reproduce this bug using minimal vimrc

### Actual behaviour

### Expected behaviour

**Comment by sainnhe** [comment]
![Screenshot_20210610_082059](https://user-images.githubusercontent.com/37491630/121445844-d76dc380-c9c4-11eb-8c45-00f3ade67f09.png)

The variable is not highlighted because there is no variable named `John`.

The curly brace is not highlighted because the left brace uses `TSPunctSpecial` which is linked to `Yellow`, while the right brace uses `TSPunctBracket` which is linked to `Fg` (i.e. white in dark bg).

I think it's a bug of nvim-treesitter, the two curly braces should use the same highlight group.

**Comment by sainnhe** [comment]
I can't fix it in color scheme level, so close this.
