### ISSUE TITLE
Use lightline/airline cofniguration with Tmuxline

### ISSUE THREAD

**Issue by mlopezgva** [sainnhe/edge#4]
Hello.

I have just set up _edge_ and it is very pleasant, well done.
However, I use the lightline colors to setup the tmux colors using [TmuxLine](/edkolev/tmuxline.vim) plugin to set up the tmux colorscheme.
The problem is that when I setup edge, lightline is just fine, but tmux is almost absolutely black (or blank...).
Luckily my setup allows me to assing an alternative to a given colorscheme, but I suppose you would want to know about this issue.

Thanks for the scheme; like I said, it's a pleasant one, and this is unusual. :-)

**Comment by sainnhe** [comment]
Both this color scheme and tmuxline have problems.

As for tmuxline, it doesn't support true colors for lightline, I've opened a PR to fix it but it hasn't been merged yet: [#101](https://github.com/edkolev/tmuxline.vim/pull/101/)

You can temporarily use [my fork](https://github.com/sainnhe/tmuxline.vim).

Because tmuxline doesn't support true colors for lightline, it will fall back to notermguicolors, but this color scheme has very weak support for notermguicolors, so you will basically see absolutely black in tmuxline.

However, this problem should be fixed in ea4a094.

**Comment by mlopezgva** [comment]
Oh, I understand. Thank you.
