### ISSUE TITLE
Any plans to migrate theme to Lua?

### ISSUE THREAD

**Issue by GentleHoneyLover** [sainnhe/edge#69]
Hi @sainnhe, thanks for the great theme! Using it everywhere (vim, neovim, vscode) and absolutely love it!

Are there any plans to migrate the theme to Lua?

More and more people are migrating to neovim with Lua configs these days. There are lots of Lua plugins that are developing more actively than their vimscript counterparts. What do you think?

**Comment by sainnhe** [comment]
No. I use both vim and neovim, I want my color schemes to work on both of them.

Btw, I didn't see any significant advantage to migrating to Lua now (performance won't be really better because the main cost is creating hi groups), whereas there is a huge disadvantage that vim users cannot use Lua color schemes.
